from typing import Optional, TYPE_CHECKING, Callable, Protocol, Any

from pl.kvgx12.wiertarbot.events import Mention as KtMention

if TYPE_CHECKING:
    from .response import IResponse
    from .abc import PyContext


class Mention(Protocol):
    def __new__(cls, thread_id: str, offset: int, length: int) -> 'Mention':
        return KtMention(thread_id, offset, length)

    def getThreadId(self) -> str: ...

    def getOffset(self) -> int: ...

    def getLength(self) -> int: ...


class Attachment(Protocol):
    def getId(self) -> Optional[str]: ...


class ImageAttachment(Attachment):
    def getWidth(self) -> Optional[int]: ...

    def getHeight(self) -> Optional[int]: ...

    def getOriginalExtension(self) -> Optional[str]: ...

    def isAnimated(self) -> Optional[bool]: ...


class Context(Protocol):
    async def pySendResponse(self, response: 'IResponse') -> None: ...

    async def pyUploadRaw(self, files: list[Any], voiceClip: bool) -> None: ...

    async def pyFetchThread(self, threadId: str) -> Any: ...

    async def pyFetchImageUrl(self, imageId: str) -> str: ...

    async def pySendText(self, event: 'MessageEvent', text: str) -> None: ...

    async def pyReactToMessage(self, event: 'MessageEvent', reaction: str) -> None: ...

    async def pyFetchRepliedTo(self, event: 'MessageEvent') -> Any: ...

    async def pySaveAttachment(self, attachment: Any) -> None: ...

    async def pyUpload(self, files: list[str], voiceClip: bool) -> list[Any]: ...


class MessageEvent(Protocol):
    def getContext(self) -> Context: ...

    def getText(self) -> str: ...

    def getAuthorId(self) -> str: ...

    def getThreadId(self) -> str: ...

    def getAt(self) -> int: ...

    def getMentions(self) -> list[Mention]: ...

    def getExternalId(self) -> str: ...

    def getReplyToId(self) -> Optional[str]: ...

    def getAttachments(self) -> list[Attachment]: ...

    def isGroup(self) -> bool: ...

    async def pyReact(self, reaction: str) -> None: ...

    # FIXME: remove this hack
    def copyWithDifferentText(cls, event: 'MessageEvent', text: str) -> 'MessageEvent': ...
