from typing import Optional, TYPE_CHECKING, Callable, Protocol

from pl.kvgx12.wiertarbot.events import Mention as KtMention

if TYPE_CHECKING:
    from .abc import Context


class Mention(Protocol):
    def __new__(cls, thread_id: str, offset: int, length: int) -> 'Mention':
        return KtMention(thread_id, offset, length)

    def getThreadId(self) -> str: ...
    def getOffset(self) -> int: ...
    def getLength(self) -> int: ...


class Attachment(Protocol):
    def getId(self) -> Optional[str]: ...


class ImageAttachment(Attachment):
    def getWidth(self) -> Optional[int]: ...
    def getHeight(self) -> Optional[int]: ...
    def getOriginalExtension(self) -> Optional[str]: ...
    def isAnimated(self) -> Optional[bool]: ...


class MessageEvent(Protocol):
    def getContext(self) -> 'Context': ...

    def getText(self) -> str: ...

    def getAuthorId(self) -> str: ...

    def getThreadId(self) -> str: ...

    def getAt(self) -> int: ...

    def getMentions(self) -> list[Mention]: ...

    def getExternalId(self) -> str: ...

    def getReplyToId(self) -> Optional[str]: ...

    def getAttachments(self) -> list[Attachment]: ...

    def isGroup(self) -> bool: ...

    async def pyReact(self, reaction: str) -> None: ...

    # FIXME: remove this hack
    def copyWithDifferentText(cls, event: 'MessageEvent', text: str) -> 'MessageEvent': ...
