from typing import Optional, TYPE_CHECKING

if TYPE_CHECKING:
    from .events import MessageEvent, Mention, UploadedFile


class IResponse:

    def getEvent(self) -> 'MessageEvent': ...
    def getText(self) -> Optional[str]: ...
    def getFiles(self) -> list['UploadedFile']: ...
    def getVoiceClip(self) -> bool: ...
    def getMentions(self) -> list['Mention']: ...
    def getReplyToId(self) -> Optional[str]: ...

    async def pySend(self) -> None: ...
