[mypy]
python_version = 3.9
;strict = true

plugins =
    returns.contrib.mypy.returns_plugin

enable_error_code =
    truthy-bool,
    redundant-expr

allow_redefinition = False
check_untyped_defs = True
disallow_untyped_calls = True
disallow_subclassing_any = True
follow_imports = silent
ignore_errors = False
ignore_missing_imports = True
implicit_reexport = True
strict_optional = True
strict_equality = True
no_implicit_optional = True
local_partial_types = True
warn_no_return = True
warn_unused_ignores = True
warn_redundant_casts = True
warn_return_any = True
warn_unused_configs = True
warn_unreachable = True
