version: "3.3"

services:
  bot:
    build: ./
#    image: kugo12/wiertarbot
    container_name: WiertarBot
    volumes:
      - ./application.yml:/app/application.yml
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
