version: 2.1

executors:
  default:
    docker:
      - image: cimg/base:current

  jdk:
    docker:
      - image: cimg/openjdk:17.0

orbs:
  gradle: circleci/gradle@3.0.0

commands:
  skip_if_files_not_changed:
    parameters:
      files:
        type: string
    steps:
      - run:
          name: Check if << parameters.files >> changed
          command: |
            CHANGED=$(git diff --name-only "<< pipeline.git.base_revision >>" -- .circleci << parameters.files >>)
            
            echo "$CHANGED"
            if [ -z "$CHANGED" ]; then
              echo "Found nothing changed matching << parameters.files >>, skipping"
              circleci-agent step halt
            fi
  docker_build:
    parameters:
      context:
        type: string
      image:
        type: string
      dockerfile:
        type: string
        default: Dockerfile
    steps:
      - setup_remote_docker:
          version: 20.10.18
      - run:
          name: Docker login
          command: docker login --username=$DOCKERHUB_USER --password=$DOCKERHUB_TOKEN
      - run:
          name: Build and push docker image
          command: >
            docker buildx build --progress=plain --push
            -t "$DOCKERHUB_USER/<< parameters.image >>:$(uname -m)-${CIRCLE_SHA1}"
            -t "$DOCKERHUB_USER/<< parameters.image >>:latest"
            -f "<< parameters.context >>/<< parameters.dockerfile >>" "<< parameters.context >>"

jobs:
  build_and_push_core:
    executor: jdk
    steps:
      - checkout
      - skip_if_files_not_changed:
          files: services/core build.gradle.kts
      - gradle/with_cache:
          deps_checksum_file: build.gradle.kts services/core/build.gradle.kts
          steps:
            - run: ./gradlew :services:core:bootJar
      - docker_build:
          image: wiertarbot
          context: services/core

  build_and_push_ttrs_api:
    executor: default
    steps:
      - checkout
      - skip_if_files_not_changed:
          files: services/ttrs-api
      - docker_build:
          image: wiertarbot-ttrs-api
          context: services/ttrs-api

  trigger_deployment:
    executor: default
    steps:
      - run:
          name: Trigger deployment
          command: |
            curl -fX POST \
              -F token=$GITLAB_WB_D_TOKEN \
              -F ref=main \
              -F "variables[CI_SOURCE]=WiertarBot" \
              $GITLAB_WB_D_URL > /dev/null


workflows:
  default:
    when:
      equal: [ main, << pipeline.git.branch >> ]

    jobs:
      - build_and_push_ttrs_api:
          context: [dockerhub]

      - build_and_push_core:
          context: [dockerhub]

      - trigger_deployment:
          context: [gitlab]
          requires: [build_and_push_core, build_and_push_ttrs_api]
