from _typeshed import Incomplete
from decimal import Decimal

class RatesNotAvailableError(Exception): ...
class DecimalFloatMismatchError(Exception): ...

class Common:
    def __init__(self, force_decimal: bool = ...) -> None: ...

class CurrencyRates(Common):
    def get_rates(self, base_cur: str, date_obj: Incomplete | None = ...): ...
    def get_rate(self, base_cur: str, dest_cur: str, date_obj: Incomplete | None = ...) -> float | Decimal: ...
    def convert(self, base_cur: str, dest_cur: str, amount: int | float | Decimal, date_obj: Incomplete | None = ...) -> float | Decimal: ...

get_rates: Incomplete
get_rate: Incomplete
convert: Incomplete

class CurrencyCodes:
    def __init__(self) -> None: ...
    def get_symbol(self, currency_code): ...
    def get_currency_name(self, currency_code): ...
    def get_currency_code_from_symbol(self, symbol): ...

get_symbol: Incomplete
get_currency_name: Incomplete
get_currency_code_from_symbol: Incomplete
