wiertarbot:
  email: ""
  password: ""
  datr: ""

  cat-api:
    key: ""

spring:
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: postgres

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest