from . import PreProcessorRegex as PreProcessorRegex, PreProcessorSub as PreProcessorSub, symbols as symbols

def tone_marks(text): ...
def end_of_line(text): ...
def abbreviations(text): ...
def word_sub(text): ...
