import datetime
from typing import Any, Iterable, Mapping, Optional, Sequence

def int_or_none(inp: Any) -> Optional[int]: ...
def get_limits(limit: Optional[int], max_limit: int) -> Iterable[int]: ...
def json_minimal(data: Any) -> str: ...
def strip_json_cruft(text: str) -> str: ...
def parse_json(text: str) -> Any: ...
def generate_offline_threading_id(): ...
def remove_version_from_module(module): ...
def get_jsmods_require(require) -> Mapping[str, Sequence[Any]]: ...
def get_jsmods_define(define) -> Mapping[str, Mapping[str, Any]]: ...
def mimetype_to_key(mimetype: str) -> str: ...
def get_url_parameter(url: str, param: str) -> Optional[str]: ...
def seconds_to_datetime(timestamp_in_seconds: float) -> datetime.datetime: ...
def millis_to_datetime(timestamp_in_milliseconds: int) -> datetime.datetime: ...
def datetime_to_seconds(dt: datetime.datetime) -> int: ...
def datetime_to_millis(dt: datetime.datetime) -> int: ...
def seconds_to_timedelta(seconds: float) -> datetime.timedelta: ...
def millis_to_timedelta(milliseconds: int) -> datetime.timedelta: ...
def timedelta_to_seconds(td: datetime.timedelta) -> int: ...
def now() -> datetime.datetime: ...
def search_for_dtsg(obj: Any) -> Optional[Mapping[str, Any]]: ...
