version: "3.3"

services:
  bot:
    build: ..
    volumes:
      - ./application.yml:/app/application.yml
      - ./data:/app/data:Z
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports: ["9090:15672"]

volumes:
  db:
